
name: Fix Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to fix'
        required: true

jobs:
  fix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: releases/${{ github.event.inputs.release_version }}

