
name: Create Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.2'

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter and Tests
        run: |
          npm run lint
          npm run test

      - name: Build Docker Image
        run: |
          docker build -t cr.yandex/fv4h9jo8f0q7hvsvuh14/app:${{ github.run_number }} .
          docker tag cr.yandex/fv4h9jo8f0q7hvsvuh14/app:${{ github.run_number }} cr.yandex/<идентификатор_реестра>/app:${{ github.run_number }}_latest

      - name: Push Docker Image
        run: |
          docker push cr.yandex/fv4h9jo8f0q7hvsvuh14/app:${{ github.run_number }}
          docker push cr.yandex/fv4h9jo8f0q7hvsvuh14/app:${{ github.run_number }}_latest

